# Generated by Django 4.2.16 on 2024-09-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_title', models.CharField(max_length=255)),
                ('lecture_content', models.TextField()),
                ('lecture_summary', models.TextField()),
                ('thumbnail_url', models.URLField(max_length=255)),
                ('semester', models.CharField(max_length=50)),
                ('keywords', models.ManyToManyField(related_name='lectures', to='STT.keyword')),
            ],
        ),
    ]
