# Generated by Django 5.1.1 on 2024-09-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stopword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=100)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
