# Generated by Django 4.2.16 on 2024-10-11 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Word",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("word", models.CharField(max_length=50)),
                ("definition", models.CharField(max_length=255)),
                ("example_sentence", models.CharField(max_length=255)),
                ("example_meaning", models.CharField(max_length=255)),
            ],
        ),
    ]
